import oracledb
import json
from typing import List, Dict

def load_config(path: str = "config_oracle.json") -> Dict[str,str]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def connect_oracle(config: Dict[str,str]):
    """
    Conecta em modo thin (puramente Python), sem passar encoding.
    """
    return oracledb.connect(
            user=config["username"],
            password=config["password"],
            dsn=config["dsn"]
    )


def save_to_oracle(records: List[Dict], conn):
    cur = conn.cursor()
    cur.execute("""
    BEGIN
        EXECUTE IMMEDIATE '
          CREATE TABLE perdas_colheita (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            fazenda VARCHAR2(100),
            safra NUMBER,
            toneladas_m NUMBER,
            toneladas_man NUMBER,
            loss_percent NUMBER
          )';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
    END;""")
    for r in records:
        cur.execute("""
        INSERT INTO perdas_colheita
          (fazenda, safra, toneladas_m, toneladas_man, loss_percent)
        VALUES (:f, :s, :tm, :tman, :lp)
        """, f=r["fazenda"],
             s=r["safra"],
             tm=r["toneladas_mecanica"],
             tman=r["toneladas_manual"],
             lp=r["loss"])
    conn.commit()
    cur.close()
    conn.close()
